apiVersion: apps/v1
kind: Deployment
metadata:
  name: MongoExpress
  namespace: mongo-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MongoExpress
  template:
    metadata:
      labels:
        app: MongoExpress
    spec:
      containers:
        - name: MongoExpress
          image: mongo-express
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: "MongoDB-service"
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: "admin"
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: "password"
          ports:
            - containerPort: 8081
